# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/ethan/Documents/cool projects/NES emulator"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/ethan/Documents/cool projects/NES emulator"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/ethan/Documents/cool projects/NES emulator/CMakeFiles" "/home/ethan/Documents/cool projects/NES emulator//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/ethan/Documents/cool projects/NES emulator/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

Bus.o: Bus.cpp.o
.PHONY : Bus.o

# target to build an object file
Bus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Bus.cpp.o
.PHONY : Bus.cpp.o

Bus.i: Bus.cpp.i
.PHONY : Bus.i

# target to preprocess a source file
Bus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Bus.cpp.i
.PHONY : Bus.cpp.i

Bus.s: Bus.cpp.s
.PHONY : Bus.s

# target to generate assembly for a file
Bus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Bus.cpp.s
.PHONY : Bus.cpp.s

CPU.o: CPU.cpp.o
.PHONY : CPU.o

# target to build an object file
CPU.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CPU.cpp.o
.PHONY : CPU.cpp.o

CPU.i: CPU.cpp.i
.PHONY : CPU.i

# target to preprocess a source file
CPU.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CPU.cpp.i
.PHONY : CPU.cpp.i

CPU.s: CPU.cpp.s
.PHONY : CPU.s

# target to generate assembly for a file
CPU.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CPU.cpp.s
.PHONY : CPU.cpp.s

Cartridge.o: Cartridge.cpp.o
.PHONY : Cartridge.o

# target to build an object file
Cartridge.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Cartridge.cpp.o
.PHONY : Cartridge.cpp.o

Cartridge.i: Cartridge.cpp.i
.PHONY : Cartridge.i

# target to preprocess a source file
Cartridge.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Cartridge.cpp.i
.PHONY : Cartridge.cpp.i

Cartridge.s: Cartridge.cpp.s
.PHONY : Cartridge.s

# target to generate assembly for a file
Cartridge.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Cartridge.cpp.s
.PHONY : Cartridge.cpp.s

Helpers.o: Helpers.cpp.o
.PHONY : Helpers.o

# target to build an object file
Helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Helpers.cpp.o
.PHONY : Helpers.cpp.o

Helpers.i: Helpers.cpp.i
.PHONY : Helpers.i

# target to preprocess a source file
Helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Helpers.cpp.i
.PHONY : Helpers.cpp.i

Helpers.s: Helpers.cpp.s
.PHONY : Helpers.s

# target to generate assembly for a file
Helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Helpers.cpp.s
.PHONY : Helpers.cpp.s

PPU.o: PPU.cpp.o
.PHONY : PPU.o

# target to build an object file
PPU.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/PPU.cpp.o
.PHONY : PPU.cpp.o

PPU.i: PPU.cpp.i
.PHONY : PPU.i

# target to preprocess a source file
PPU.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/PPU.cpp.i
.PHONY : PPU.cpp.i

PPU.s: PPU.cpp.s
.PHONY : PPU.s

# target to generate assembly for a file
PPU.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/PPU.cpp.s
.PHONY : PPU.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

mappers/Mapper.o: mappers/Mapper.cpp.o
.PHONY : mappers/Mapper.o

# target to build an object file
mappers/Mapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mappers/Mapper.cpp.o
.PHONY : mappers/Mapper.cpp.o

mappers/Mapper.i: mappers/Mapper.cpp.i
.PHONY : mappers/Mapper.i

# target to preprocess a source file
mappers/Mapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mappers/Mapper.cpp.i
.PHONY : mappers/Mapper.cpp.i

mappers/Mapper.s: mappers/Mapper.cpp.s
.PHONY : mappers/Mapper.s

# target to generate assembly for a file
mappers/Mapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mappers/Mapper.cpp.s
.PHONY : mappers/Mapper.cpp.s

mappers/Mapper000.o: mappers/Mapper000.cpp.o
.PHONY : mappers/Mapper000.o

# target to build an object file
mappers/Mapper000.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mappers/Mapper000.cpp.o
.PHONY : mappers/Mapper000.cpp.o

mappers/Mapper000.i: mappers/Mapper000.cpp.i
.PHONY : mappers/Mapper000.i

# target to preprocess a source file
mappers/Mapper000.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mappers/Mapper000.cpp.i
.PHONY : mappers/Mapper000.cpp.i

mappers/Mapper000.s: mappers/Mapper000.cpp.s
.PHONY : mappers/Mapper000.s

# target to generate assembly for a file
mappers/Mapper000.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mappers/Mapper000.cpp.s
.PHONY : mappers/Mapper000.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... Bus.o"
	@echo "... Bus.i"
	@echo "... Bus.s"
	@echo "... CPU.o"
	@echo "... CPU.i"
	@echo "... CPU.s"
	@echo "... Cartridge.o"
	@echo "... Cartridge.i"
	@echo "... Cartridge.s"
	@echo "... Helpers.o"
	@echo "... Helpers.i"
	@echo "... Helpers.s"
	@echo "... PPU.o"
	@echo "... PPU.i"
	@echo "... PPU.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mappers/Mapper.o"
	@echo "... mappers/Mapper.i"
	@echo "... mappers/Mapper.s"
	@echo "... mappers/Mapper000.o"
	@echo "... mappers/Mapper000.i"
	@echo "... mappers/Mapper000.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

