# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/arnavswami/NESSim/NES-Emulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/arnavswami/NESSim/NES-Emulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arnavswami/NESSim/NES-Emulator/CMakeFiles /Users/arnavswami/NESSim/NES-Emulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arnavswami/NESSim/NES-Emulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named cputest

# Build rule for target.
cputest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cputest
.PHONY : cputest

# fast build rule for target.
cputest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cputest.dir/build.make CMakeFiles/cputest.dir/build
.PHONY : cputest/fast

CPU.o: CPU.cpp.o
.PHONY : CPU.o

# target to build an object file
CPU.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CPU.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/CPU.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cputest.dir/build.make CMakeFiles/cputest.dir/CPU.cpp.o
.PHONY : CPU.cpp.o

CPU.i: CPU.cpp.i
.PHONY : CPU.i

# target to preprocess a source file
CPU.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CPU.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/CPU.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cputest.dir/build.make CMakeFiles/cputest.dir/CPU.cpp.i
.PHONY : CPU.cpp.i

CPU.s: CPU.cpp.s
.PHONY : CPU.s

# target to generate assembly for a file
CPU.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CPU.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/CPU.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cputest.dir/build.make CMakeFiles/cputest.dir/CPU.cpp.s
.PHONY : CPU.cpp.s

Helpers.o: Helpers.cpp.o
.PHONY : Helpers.o

# target to build an object file
Helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Helpers.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/Helpers.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cputest.dir/build.make CMakeFiles/cputest.dir/Helpers.cpp.o
.PHONY : Helpers.cpp.o

Helpers.i: Helpers.cpp.i
.PHONY : Helpers.i

# target to preprocess a source file
Helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Helpers.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/Helpers.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cputest.dir/build.make CMakeFiles/cputest.dir/Helpers.cpp.i
.PHONY : Helpers.cpp.i

Helpers.s: Helpers.cpp.s
.PHONY : Helpers.s

# target to generate assembly for a file
Helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Helpers.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/Helpers.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cputest.dir/build.make CMakeFiles/cputest.dir/Helpers.cpp.s
.PHONY : Helpers.cpp.s

NES.o: NES.cpp.o
.PHONY : NES.o

# target to build an object file
NES.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NES.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/NES.cpp.o
.PHONY : NES.cpp.o

NES.i: NES.cpp.i
.PHONY : NES.i

# target to preprocess a source file
NES.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NES.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/NES.cpp.i
.PHONY : NES.cpp.i

NES.s: NES.cpp.s
.PHONY : NES.s

# target to generate assembly for a file
NES.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NES.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/NES.cpp.s
.PHONY : NES.cpp.s

debug.o: debug.cpp.o
.PHONY : debug.o

# target to build an object file
debug.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/debug.cpp.o
.PHONY : debug.cpp.o

debug.i: debug.cpp.i
.PHONY : debug.i

# target to preprocess a source file
debug.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/debug.cpp.i
.PHONY : debug.cpp.i

debug.s: debug.cpp.s
.PHONY : debug.s

# target to generate assembly for a file
debug.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/debug.cpp.s
.PHONY : debug.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

tests/cputest.o: tests/cputest.cpp.o
.PHONY : tests/cputest.o

# target to build an object file
tests/cputest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cputest.dir/build.make CMakeFiles/cputest.dir/tests/cputest.cpp.o
.PHONY : tests/cputest.cpp.o

tests/cputest.i: tests/cputest.cpp.i
.PHONY : tests/cputest.i

# target to preprocess a source file
tests/cputest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cputest.dir/build.make CMakeFiles/cputest.dir/tests/cputest.cpp.i
.PHONY : tests/cputest.cpp.i

tests/cputest.s: tests/cputest.cpp.s
.PHONY : tests/cputest.s

# target to generate assembly for a file
tests/cputest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cputest.dir/build.make CMakeFiles/cputest.dir/tests/cputest.cpp.s
.PHONY : tests/cputest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cputest"
	@echo "... debug"
	@echo "... main"
	@echo "... CPU.o"
	@echo "... CPU.i"
	@echo "... CPU.s"
	@echo "... Helpers.o"
	@echo "... Helpers.i"
	@echo "... Helpers.s"
	@echo "... NES.o"
	@echo "... NES.i"
	@echo "... NES.s"
	@echo "... debug.o"
	@echo "... debug.i"
	@echo "... debug.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tests/cputest.o"
	@echo "... tests/cputest.i"
	@echo "... tests/cputest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

